services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visa_captcha_solver
    env_file:
      - ./.env
    command: ["python3.12", "src/scrape.py"]
    ipc: host